version: '3'

services:
  node_app:
    container_name: backend_app
    restart: always
    ports:
      - "8080:3050"
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    ports:
      - "54036:5432"
    environment:
      POSTGRES_PASSWORD: db-pass
      POSTGRES_USER: db-user
      POSTGRES_DB: db-name
    volumes:
      - app_data:/var/lib/postgresql/data

  node_test_app:
    container_name: backend_test
    build:
      context: .
      dockerfile: app.Dockerfile

volumes:
  app_data: